web/router.ex
defmodule Rundot.Router do
  use Rundot.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Rundot do
    pipe_through :browser # Use the default browser stack

    get "/", RunController, :index

    resources "/runs", RunController
    resources "/registrations", RegistrationController, only: [:new, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Rundot do
  #   pipe_through :api
  # end
end

lib/rundot/ecto_enums.ex
import EctoEnum

defenum DistanceUnitEnum, mi: 0, km: 1

lib/rundot/endpoint.ex
defmodule Rundot.Endpoint do
  use Phoenix.Endpoint, otp_app: :rundot

  socket "/socket", Rundot.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :rundot, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_rundot_key",
    signing_salt: "M576W8lg"

  plug Rundot.Router
end

lib/rundot/repo.ex
defmodule Rundot.Repo do
  use Ecto.Repo, otp_app: :rundot
end

web/models/registration.ex
defmodule Rundot.Registration do
  import Ecto.Changeset, only: [put_change: 3]

  def create(changeset, repo) do
    changeset
    |> put_change(:crypted_password, hashed_password(changeset.params["password"]))
    |> repo.insert()
  end

  defp hashed_password(password) do
    Comeonin.Bcrypt.hashpwsalt(password)
  end
end

web/models/run.ex
defmodule Rundot.Run do
  use Rundot.Web, :model

  @primary_key {:id, :binary_id, autogenerate: true}
  @derive {Phoenix.Param, key: :id}

  schema "runs" do
    field :start_time, Ecto.DateTime
    field :end_time, Ecto.DateTime
    field :distance, :float
    field :distance_unit, DistanceUnitEnum

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:start_time, :end_time, :distance, :distance_unit])
    |> validate_required([:start_time, :end_time, :distance, :distance_unit])
  end
end

web/models/user.ex
defmodule Rundot.User do
  use Rundot.Web, :model

  schema "users" do
    field :email, :string
    field :crypted_password, :string
    field :password, :string, virtual: true

    timestamps()
  end

  @required_fields ~w(email password)
  @optional_fields ~w(crypted_password)

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, @required_fields, @optional_fields)
    |> unique_constraint(:email)
    |> validate_format(:email, ~r/@/) # FIXME: crude validation
    |> validate_length(:password, min: 6)
  end
end

web/controllers/registration_controller.ex
defmodule Rundot.RegistrationController do
  use Rundot.Web, :controller
  alias Rundot.User

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render conn, changeset: changeset
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.changeset(%User{}, user_params)

    case Rundot.Registration.create(changeset, Rundot.Repo) do
      {:ok, changeset} ->
        conn
        |> put_flash(:info, "Welcome to rundot!")
        |> redirect(to: "/")
      {:error, changeset} ->
        conn
        |> put_flash(:info, "Something didn't quite work there...")
        |> redirect(to: "new.html", changeset: changeset)
    end
  end
end

web/controllers/run_controller.ex
require IEx
defmodule Rundot.RunController do
  use Rundot.Web, :controller
  use Timex

  alias Rundot.Run

  def index(conn, _params) do
    runs = Repo.all(Run)
    render(conn, "index.html", runs: runs)
  end

  def new(conn, _params) do
    render(conn, "new.html", changeset: Run.changeset(%Run{}))
  end

  def create(conn, %{"run" => run_params}) do
    case Repo.insert(Run.changeset(%Run{}, run_params)) do
      {:ok, _run} ->
        conn
        |> put_flash(:info, "Run created successfully.")
        |> redirect(to: run_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    render(conn, "show.html", run: Repo.get!(Run, id))
  end

  def edit(conn, %{"id" => id}) do
    run = Repo.get!(Run, id)
    render(conn, "edit.html", run: run, changeset: Run.changeset(run))
  end

  def update(conn, %{"id" => id, "run" => run_params}) do
    run = Repo.get!(Run, id)

    case Repo.update(Run.changeset(run, run_params)) do
      {:ok, run} ->
        conn
        |> put_flash(:info, "Run updated successfully.")
        |> redirect(to: run_path(conn, :show, run))
      {:error, changeset} ->
        render(conn, "edit.html", run: run, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    run = Repo.get!(Run, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(run)

    conn
    |> put_flash(:info, "Run deleted successfully.")
    |> redirect(to: run_path(conn, :index))
  end
end

web/views/error_view.ex
defmodule Rundot.ErrorView do
  use Rundot.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Rundot.LayoutView do
  use Rundot.Web, :view
end

web/views/registration_view.ex
defmodule Rundot.RegistrationView do
  use Rundot.Web, :view
end

web/views/run_view.ex
defmodule Rundot.RunView do
  use Rundot.Web, :view
  use Timex

  def new_run_link(conn, label \\ "New run") do
    link(label, to: run_path(conn, :new))
  end

  def get_today_as_date do
    t = Timex.local |> Timex.to_date |> Timex.to_datetime(:local)
    %Ecto.DateTime{year: t.year, month: t.month, day: t.day}
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>run.</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <div class="text-right">
          <%= link "Register", to: registration_path(@conn, :new) %>
        </div>
        <h1>run.</h1>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/run/edit.html.eex
<%= render "form.html", changeset: @changeset,
                        action: run_path(@conn, :update, @run) %>

<%= link "Back", to: run_path(@conn, :index) %>

web/templates/run/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :start_time, class: "control-label" %>
    <%= datetime_select f, :start_time, second: [], class: "form-control", default: get_today_as_date %>
    <%= error_tag f, :start_time %>
  </div>

  <div class="form-group">
    <%= label f, :end_time, class: "control-label" %>
    <%= datetime_select f, :end_time, second: [], class: "form-control", default: get_today_as_date %>
    <%= error_tag f, :end_time %>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <%= label f, :distance, class: "control-label" %>
    </div>
    <div class="col-sm-10">
      <div class="form-group">
        <%= number_input f, :distance, step: "any", class: "form-control", id: "run-distance-raw-value" %>
        <%= error_tag f, :distance %>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="form-group">
        <%= select f, :distance_unit, DistanceUnitEnum.__enum_map__() |> Enum.map(fn({x,_})-> x end), class: "form-control" %>
        <%= error_tag f, :distance_unit %>
      </div>
    </div>
  </div>

  <div class="jumbotron">
    <p>You ran for <strong><span id="run-elapsed-time"></span></strong></h2>
    <p>Your average speed was <strong><span id="run-average-speed"></span> <span class="run-distance-unit"></span>/hr</strong></p>
    &nbsp;
    <h2>Nice work!</h2>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/run/index.html.eex
<%= if Enum.empty?(@runs) do %>
  <div class="jumbotron">
    <p>You haven't logged any runs yet...</p>
    <%= new_run_link @conn, "Get started now" %>
  </div>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th>Start time</th>
        <th>End time</th>
        <th>Distance</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= for run <- @runs do %>
        <tr>
          <td><%= run.start_time %></td>
          <td><%= run.end_time %></td>
          <td><%= "#{run.distance} #{run.distance_unit}" %></td>
          <td class="text-right">
            <%= link "Show", to: run_path(@conn, :show, run), class: "btn btn-default btn-xs" %>
            <%= link "Edit", to: run_path(@conn, :edit, run), class: "btn btn-default btn-xs" %>
            <%= link "Delete", to: run_path(@conn, :delete, run), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= new_run_link @conn %>
<% end %>

web/templates/run/new.html.eex
<%= render "form.html", changeset: @changeset,
                        action: run_path(@conn, :create) %>

<%= link "Back", to: run_path(@conn, :index) %>

web/templates/run/show.html.eex
<ul>
  <li>
    <strong>Start time:</strong>
    <%= @run.start_time %>
  </li>
  <li>
    <strong>End time:</strong>
    <%= @run.end_time %>
  </li>
  <li>
    <strong>Distance:</strong>
    <%= "#{@run.distance} #{@run.distance_unit}" %>
  </li>
</ul>

<%= link "Edit", to: run_path(@conn, :edit, @run) %>
&nbsp;
<%= link "Back", to: run_path(@conn, :index) %>